-- MySQL Script generated by MySQL Workbench
-- Thu Jul  6 10:49:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema watersystem
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `watersystem` ;

-- -----------------------------------------------------
-- Schema watersystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `watersystem` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `watersystem` ;

-- -----------------------------------------------------
-- Table `watersystem`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `watersystem`.`categoria` ;

CREATE TABLE IF NOT EXISTS `watersystem`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `watersystem`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `watersystem`.`usuario` ;

CREATE TABLE IF NOT EXISTS `watersystem`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `idade` INT NOT NULL,
  `categoria` INT NULL DEFAULT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(300) NULL,
  `password` VARCHAR(100) NULL,
  `nivel` VARCHAR(100) NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `categoria` (`categoria` ASC) VISIBLE,
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`categoria`)
    REFERENCES `watersystem`.`categoria` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `watersystem`.`residencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `watersystem`.`residencia` ;

CREATE TABLE IF NOT EXISTS `watersystem`.`residencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `complemento` VARCHAR(255) NULL DEFAULT NULL,
  `apelido` VARCHAR(255) NULL DEFAULT NULL,
  `usuario` INT NULL DEFAULT NULL,
  `cidade` VARCHAR(255) NULL DEFAULT NULL,
  `estado` VARCHAR(255) NULL DEFAULT NULL,
  `bairro` VARCHAR(255) NULL DEFAULT NULL,
  `endereco` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario` (`usuario` ASC) VISIBLE,
  CONSTRAINT `residencia_ibfk_1`
    FOREIGN KEY (`usuario`)
    REFERENCES `watersystem`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `watersystem`.`periodo_consumo_alerta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `watersystem`.`periodo_consumo_alerta` ;

CREATE TABLE IF NOT EXISTS `watersystem`.`periodo_consumo_alerta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `periodo` DATE NULL DEFAULT NULL,
  `horas` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `watersystem`.`alerta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `watersystem`.`alerta` ;

CREATE TABLE IF NOT EXISTS `watersystem`.`alerta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `m3` INT NULL DEFAULT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `residencia` INT NULL DEFAULT NULL,
  `periodo` INT NULL DEFAULT NULL,
  `valor_periodo` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `residencia` (`residencia` ASC) VISIBLE,
  INDEX `periodo` (`periodo` ASC) VISIBLE,
  CONSTRAINT `alerta_ibfk_1`
    FOREIGN KEY (`residencia`)
    REFERENCES `watersystem`.`residencia` (`id`),
  CONSTRAINT `alerta_ibfk_2`
    FOREIGN KEY (`periodo`)
    REFERENCES `watersystem`.`periodo_consumo_alerta` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `watersystem`.`consumo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `watersystem`.`consumo` ;

CREATE TABLE IF NOT EXISTS `watersystem`.`consumo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `h_inicial` TIME NULL DEFAULT NULL,
  `h_final` TIME NULL DEFAULT NULL,
  `dias` INT NULL DEFAULT NULL,
  `residencia` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `residencia` (`residencia` ASC) VISIBLE,
  CONSTRAINT `consumo_ibfk_1`
    FOREIGN KEY (`residencia`)
    REFERENCES `watersystem`.`residencia` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `watersystem`.`historico_consumo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `watersystem`.`historico_consumo` ;

CREATE TABLE IF NOT EXISTS `watersystem`.`historico_consumo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datahora` DATETIME NULL DEFAULT NULL,
  `m3` INT NULL DEFAULT NULL,
  `residencia` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `residencia` (`residencia` ASC) VISIBLE,
  CONSTRAINT `historico_consumo_ibfk_1`
    FOREIGN KEY (`residencia`)
    REFERENCES `watersystem`.`residencia` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `watersystem`.`historico_tarifa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `watersystem`.`historico_tarifa` ;

CREATE TABLE IF NOT EXISTS `watersystem`.`historico_tarifa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  `mes` VARCHAR(255) NULL DEFAULT NULL,
  `historico_consumo` INT NULL DEFAULT NULL,
  `residencia` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `historico_consumo` (`historico_consumo` ASC) VISIBLE,
  INDEX `residencia` (`residencia` ASC) VISIBLE,
  CONSTRAINT `historico_tarifa_ibfk_1`
    FOREIGN KEY (`historico_consumo`)
    REFERENCES `watersystem`.`historico_consumo` (`id`),
  CONSTRAINT `historico_tarifa_ibfk_2`
    FOREIGN KEY (`residencia`)
    REFERENCES `watersystem`.`residencia` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `watersystem`.`vazamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `watersystem`.`vazamento` ;

CREATE TABLE IF NOT EXISTS `watersystem`.`vazamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datahora` DATETIME NULL DEFAULT NULL,
  `observacao` VARCHAR(255) NULL DEFAULT NULL,
  `consumo` INT NULL DEFAULT NULL,
  `residencia` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `consumo` (`consumo` ASC) VISIBLE,
  INDEX `residencia` (`residencia` ASC) VISIBLE,
  CONSTRAINT `vazamento_ibfk_1`
    FOREIGN KEY (`consumo`)
    REFERENCES `watersystem`.`consumo` (`id`),
  CONSTRAINT `vazamento_ibfk_2`
    FOREIGN KEY (`residencia`)
    REFERENCES `watersystem`.`residencia` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
